In [20]:
#Zeros function
import numpy as np
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#ones function
import numpy as np
arr=np.ones((5,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
#eye function = identity matrix
import numpy as np
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
#diagonal function = diagonal matrix
import numpy as np
arr=np.diag([5,3,6,8])
print(arr)

[[5 0 0 0]
 [0 3 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [25]:
#randint function
import numpy as np
arr=np.random.randint(10,51,18)            #(from,10 to 51, number of elements you want)
print(arr)
rsp=arr.reshape(6,3)
rrsp=arr.reshape(9,-1)                      # -1 is used to automatically decide shape of array
print(rsp)
print("Number of dimention of rsp is: ",rsp.shape)       #rsp.shape is used to find number of dimentions of array
print("Dimention of array of rsp is: ",rsp.ndim)
print(rrsp)
print("Number of dimention of rrsp is: ",rsp.shape)       #rsp.shape is used to find number of dimentions of array
print("Dimention of array of rrsp is: ",rsp.ndim)               #ndim used to find dimention of an array

[33 39 35 19 11 19 34 22 45 18 46 13 30 17 22 10 17 21]
[[33 39 35]
 [19 11 19]
 [34 22 45]
 [18 46 13]
 [30 17 22]
 [10 17 21]]
Number of dimention of rsp is:  (6, 3)
Dimention of array of rsp is:  2
[[33 39]
 [35 19]
 [11 19]
 [34 22]
 [45 18]
 [46 13]
 [30 17]
 [22 10]
 [17 21]]
Number of dimention of rrsp is:  (6, 3)
Dimention of array of rrsp is:  2


In [13]:
#rand function = returns values between 0 to 1
import numpy as np  
arr=np.random.rand(5)
print(arr)
#"Another form of writing rand function"
print("Another example: ")
arr1=np.random.rand(2,3)
print(arr1)

[0.39297998 0.29604683 0.29073727 0.30545682 0.05063057]
Another example: 
[[0.26742081 0.08697196 0.38642935]
 [0.23774407 0.92677094 0.89071413]]


In [15]:
#randn function = it generates random positive nadd negative numbers near to zero 
import numpy as np
arr=np.random.randn(8)
print(arr)
#"Another way of writing randn function"
print("Another example: ")
arr1=np.random.rand(3,4)
print(arr1)

[-0.79761469  0.0100316  -0.26639838  1.27602045 -1.57096217  1.14937557
  0.14287887 -0.20234278]
Another example: 
[[0.99880192 0.89318879 0.19422953 0.78307501]
 [0.26998377 0.17774961 0.93695666 0.76161667]
 [0.67567506 0.6414372  0.99411538 0.48916669]]


In [1]:
x = int(input("Enter number: "))
i = (x//10) + 1
print(i)

3
