# Slicing of 1D Array 

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [3]:
import numpy as np
a=[]
size=int(input("Enter number of element you want: "))
for i in range (size):
    val=int(input("Enter Values: "))
    a.append(val)
arr=np.array(a)
print(arr)
print ("Entered elements are: ")
for i in range (arr.size):
    print(arr[i])
#for sum of elememts 
sum=0
for i in range (arr.size):
    sum=sum+arr[i]
print("Sum of elements is: ",sum)

#SLicing of 1D aarray :
print("Element having indexing 2 to 5 are: ")
arr1=arr[2:6]
print(arr1) 

Enter number of element you want: 6
Enter Values: 10
Enter Values: 20
Enter Values: 30
Enter Values: 40
Enter Values: 50
Enter Values: 60
[10 20 30 40 50 60]
Entered elements are: 
10
20
30
40
50
60
Sum of elements is:  210
Element having indexing 2 to 5 are: 
[30 40 50 60]


# Slicing in 2D Array

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [11]:
import numpy as np
arr=np.arange(1,26).reshape(5,5)
print("The required array is: ")
print(arr)
arr[2,2:5]


The required array is: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([13, 14, 15])

In [12]:
import numpy as np
arr=np.arange(1,26).reshape(5,5)
print("The required array is: ")
print(arr)
arr[:2,2:5]

The required array is: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [13]:
import numpy as np
arr=np.arange(1,26).reshape(5,5)
print("The required array is: ")
print(arr)
arr[2:,2:5]

The required array is: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [14]:
import numpy as np
arr=np.arange(1,26).reshape(5,5)
print("The required array is: ")
print(arr)
arr[2:5,2]

The required array is: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([13, 18, 23])

In [15]:
import numpy as np
arr=np.arange(1,26).reshape(5,5)
print("The required array is: ")
print(arr)
arr[2:5,2:]

The required array is: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [16]:
import numpy as np
arr=np.arange(1,26).reshape(5,5)
print("The required array is: ")
print(arr)
arr[2:5,:5]

The required array is: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
import numpy as np
arr=np.arange(1,26).reshape(5,5)
print("The required array is: ")
print(arr)
arr[2:5:2,:5:2]

The required array is: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[11, 13, 15],
       [21, 23, 25]])