# Stacking in 1-D array

In [19]:
import numpy as np
arr1=np.array([10,20,30,40,50])
arr2=np.array([60,70,80,90,100])
np.hstack((arr1,arr2))      # it will append arr2 ahead of arr1 in horizontal direction

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [7]:
import numpy as np
arr1=np.array([10,20,30,40,50])
arr2=np.array([60,70,80,90,100])
np.vstack((arr1,arr2))      # it will append arr2 below arr1 in vertical direction

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

# Stacking in 2-D array 

In [17]:
import numpy as np
np.random.seed(12)
arr1=np.random.randint(1,21,9).reshape(3,3)
arr2=np.random.randint(25,100,9).reshape(3,3)
np.hstack((arr1,arr2))              # it will append arr2 ahead of arr1 in horizontal direction

array([[12,  7, 18, 77, 30, 38],
       [ 3,  4,  4, 59, 99, 25],
       [13, 17, 18, 38, 60, 87]])

In [18]:
import numpy as np
np.random.seed(12)
arr1=np.random.randint(1,21,9).reshape(3,3)
arr2=np.random.randint(25,100,9).reshape(3,3)
np.vstack((arr1,arr2))              # it will append arr2 below arr1 in vertical direction

array([[12,  7, 18],
       [ 3,  4,  4],
       [13, 17, 18],
       [77, 30, 38],
       [59, 99, 25],
       [38, 60, 87]])