In [1]:
import numpy as np
r=int(input("Enter number of rows: "))
c=int(input("Enter number of collumns: "))
matrix=[]
for i in range (r):
    for j in range (c):
        val=int(input("Enter values: "))
        matrix.append(val)
marr=np.array(matrix)
print("Entered value: ",matrix)
print("Entered value in array: ",marr)
print("Shape of array: ",np.shape(marr))
print("Array after reshaping in 2D: ")
print(np.reshape(marr,(c,r)))

Enter number of rows: 3
Enter number of collumns: 4
Enter values: 1
Enter values: 0
Enter values: 1
Enter values: 0
Enter values: 1
Enter values: 0
Enter values: 1
Enter values: 0
Enter values: 1
Enter values: 0
Enter values: 1
Enter values: 0
Entered value:  [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
Entered value in array:  [1 0 1 0 1 0 1 0 1 0 1 0]
Shape of array:  (12,)
Array after reshaping in 2D: 
[[1 0 1]
 [0 1 0]
 [1 0 1]
 [0 1 0]]
